title: 周刊翻译计划

name: FEDarling

email: im@daodaolee.cn

description: ⛱ 周刊翻译计划，目前涉及JavaScript Weekly、Mobile Dev Weekly、Frontend Focus、React Status、Node Weekly 和 CSS Weekly期刊，希望读者可以有所收获！🥳
url: "https://fedarling.github.io"
baseurl: "/fe-translate-weekly"
repository: "FEDarling/fe-translate-weekly"
logo: "https://avatars.githubusercontent.com/u/97049302?s=400&u=9eeeeb9644d2ed3b862b8bab1a91adcf48792299&v=4"

words_per_minute: 200

social:
  name: DaoDaoLee
  links: https://github.com/daodaolee

author:
  name             : "FEDarling"
  avatar           : "https://avatars.githubusercontent.com/t/5522920?s=280&v=4"
  bio              : "Front End Darling Translate"
  location         : "HangZhou"
  email            : mailto:im@daodaolee.cn?cc=im@daodaolee.cn
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:im@daodaolee.cn?cc=im@daodaolee.cn
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: https://daodaolee.cn
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/daodaolee

minimal_mistakes_skin: dark

search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id         : 1D0PBCG9PL
  index_name             : FEDaring/translate
  search_only_api_key    : f5b98f3b48ae1f18b801944f479d17f1
  powered_by             : true

# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - JavaScript_Weekly
  - CSS_Weekly
  - Mobile_Dev_Weekly
  - Frontend_Focus
  - React_Status
  - Node_Weekly

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FEDarling"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  parse_block_html: true
  enable_coderay: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "JavaScript_Weekly"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "CSS_Weekly"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "Mobile_Dev_Weekly"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "Frontend_Focus"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "React_Status"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "Node_Weekly"
      type: pages
    values:
      layout: single
      author_profile: true
