# theme: jekyll-theme-cayman
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
markdown: GFM

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
