name: vuepress-deploy

on:
  push:
    branches: [add-deploy]
  pull_request:
    branches: [add-deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          TARGET_REPO: FEDarling/weekly-tracker
          TARGET_BRANCH: pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: public
