name: Weekly Releases
on:
  push:
    branches: [kim-working-branche]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: create-release-issue
        uses: ./.github/actions/weekly-release
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}